#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# navigate to parent of husky dir- we assume pnpm-lock is located there.
cd "$(dirname $0)/.."

LOCKFILE_CHANGED_LINES=$(git diff HEAD@{1} --stat -- pnpm-lock.yaml | wc -l)

if [ -z "${CI}" ] && [ $LOCKFILE_CHANGED_LINES -gt 0 ]; then
  echo "Detected changes to pnpm-lock.yaml. Reinstalling packages..."
  pnpm i
fi

# Regenerate prisma client + run migrations when relevant files have changed
PRISMA_CHANGED_LINES=$(git diff HEAD@{1} --stat -- packages/prisma-client/prisma | wc -l)

if [ -z "${CI}" ] && [ $PRISMA_CHANGED_LINES -gt 0 ]; then
  echo "Detected changes to Prisma schema or migration files. Regenerating client and applying migrations..."
  # ensure packages are installed
  pnpm i
  pnpm run -F prisma-client db:migrate:deploy && pnpm run -F prisma-client db:generate
fi

# return to previous working dir
cd -
