name: Test and Deploy
on:
  push:
    branches:
      - '**' # Matches all branches
  pull_request:
    branches:
      - main
      - dev

env:
  STORE_PATH: .pnpm-store

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: ./.github/actions/setup

      - name: Run Tests
        run: pnpm test

  preview-deploy:
    needs: test
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: ./.github/actions/setup

      - name: Deploy to Preview
        uses: ./.github/actions/vercel-deploy
        id: deploy
        with:
          environment: preview
          token: ${{ secrets.VERCEL_TOKEN }}

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `✅ Preview deployment is ready at: ${steps.deploy.outputs.url}`
            })

  production-deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: ./.github/actions/setup

      - name: Deploy to Production
        id: deploy
        uses: ./.github/actions/vercel-deploy
        with:
          environment: production
          token: ${{ secrets.VERCEL_TOKEN }}
